# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 15:27
from __future__ import unicode_literals

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170726_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=simditor.fields.RichTextField(verbose_name='文章正文'),
        ),
    ]
