# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170910_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qq_openid',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
