# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-14 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_qq_openid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qq_openid',
        ),
    ]
